name: Test of github action
on: [push]
jobs:
  compile:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: |
          go version
          go build -o output/
      - name: Run
        run: |
          ./output/action_test
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: action_test
          path: output/action_test