name: Test of github action
on:
  push:
    tags:
     - 'v*'
jobs:
  compile:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Testing
        run: |
          go test
      - name: Build
        run: |
          go version
          go build -o output/
      - name: Run
        run: |
          ./output/action_test
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: action_test
          path: output/action_test
